---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: table3aransiblerg
        location: ukwest
      register: rg
    - debug:
        var: rg
